# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/designerTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 700)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"#leftSubMenu QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    background-color: rgb(204, 204, 204);\n"
"}\n"
"\n"
"#leftMenu QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"#QComboBox::drop-down{\n"
"border: none;\n"
"width: 0;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame::frame_6{\n"
"background-color: rgba(157, 157, 157, 100);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("QWidget#widget{background-color: rgb(195, 195, 195);}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftMenu = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QtCore.QSize(170, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftMenu.setStyleSheet("QFrame#leftMenu{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.658, x2:1, y2:0.647409, stop:0 rgba(29, 67, 155, 255), stop:1 rgba(28, 28, 28, 255));\n"
"}\n"
"QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    background-color: rgba(255, 170, 127, 0);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 170, 127, 50);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: rgba(255, 170, 127, 150);\n"
"}\n"
"")
        self.leftMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.leftMenu)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_2 = QtWidgets.QFrame(self.leftMenu)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(5, 5, 0, 0)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(25, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/emercom.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.frame_8 = QtWidgets.QFrame(self.leftMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnHome = QtWidgets.QPushButton(self.frame_8)
        self.btnHome.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/magazine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHome.setIcon(icon)
        self.btnHome.setIconSize(QtCore.QSize(26, 26))
        self.btnHome.setObjectName("btnHome")
        self.verticalLayout_6.addWidget(self.btnHome)
        self.btnPerson = QtWidgets.QPushButton(self.frame_8)
        self.btnPerson.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btnPerson.setFont(font)
        self.btnPerson.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPerson.setIcon(icon1)
        self.btnPerson.setIconSize(QtCore.QSize(26, 26))
        self.btnPerson.setObjectName("btnPerson")
        self.verticalLayout_6.addWidget(self.btnPerson)
        self.btnTopic = QtWidgets.QPushButton(self.frame_8)
        self.btnTopic.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btnTopic.setFont(font)
        self.btnTopic.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/tema.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTopic.setIcon(icon2)
        self.btnTopic.setIconSize(QtCore.QSize(26, 26))
        self.btnTopic.setObjectName("btnTopic")
        self.verticalLayout_6.addWidget(self.btnTopic)
        self.verticalLayout_2.addWidget(self.frame_8)
        spacerItem = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_10 = QtWidgets.QFrame(self.leftMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 25)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.helpBtn = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.helpBtn.setFont(font)
        self.helpBtn.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/tasts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon3)
        self.helpBtn.setIconSize(QtCore.QSize(26, 26))
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_7.addWidget(self.helpBtn)
        self.settingBtn = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.settingBtn.setFont(font)
        self.settingBtn.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingBtn.setIcon(icon4)
        self.settingBtn.setIconSize(QtCore.QSize(26, 26))
        self.settingBtn.setObjectName("settingBtn")
        self.verticalLayout_7.addWidget(self.settingBtn)
        self.verticalLayout_2.addWidget(self.frame_10, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.leftMenu)
        self.leftSubMenu = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftSubMenu.sizePolicy().hasHeightForWidth())
        self.leftSubMenu.setSizePolicy(sizePolicy)
        self.leftSubMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.leftSubMenu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.leftSubMenu.setStyleSheet("background-color: rgb(213, 203, 203);")
        self.leftSubMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftSubMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftSubMenu.setObjectName("leftSubMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftSubMenu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.upLeftSubMenu = QtWidgets.QFrame(self.leftSubMenu)
        self.upLeftSubMenu.setStyleSheet("background-color: rgb(187, 187, 187);")
        self.upLeftSubMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upLeftSubMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upLeftSubMenu.setObjectName("upLeftSubMenu")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.upLeftSubMenu)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.closeCenterMenu_2 = QtWidgets.QPushButton(self.upLeftSubMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeCenterMenu_2.sizePolicy().hasHeightForWidth())
        self.closeCenterMenu_2.setSizePolicy(sizePolicy)
        self.closeCenterMenu_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.closeCenterMenu_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(187, 187, 187);\n"
"border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: rgb(91, 91, 91);\n"
"}\n"
"")
        self.closeCenterMenu_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeCenterMenu_2.setIcon(icon5)
        self.closeCenterMenu_2.setIconSize(QtCore.QSize(24, 24))
        self.closeCenterMenu_2.setObjectName("closeCenterMenu_2")
        self.horizontalLayout_6.addWidget(self.closeCenterMenu_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.upLeftSubMenu, 0, QtCore.Qt.AlignTop)
        self.stackedWidgetLeftMenu = QtWidgets.QStackedWidget(self.leftSubMenu)
        self.stackedWidgetLeftMenu.setStyleSheet("")
        self.stackedWidgetLeftMenu.setObjectName("stackedWidgetLeftMenu")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_9.setContentsMargins(0, 21, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.page_1)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btnTask = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTask.sizePolicy().hasHeightForWidth())
        self.btnTask.setSizePolicy(sizePolicy)
        self.btnTask.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(False)
        self.btnTask.setFont(font)
        self.btnTask.setStyleSheet("QPushButton {\n"
"  background-color: rgb(213, 203, 203);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: rgb(91, 91, 91);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/bookmark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTask.setIcon(icon6)
        self.btnTask.setIconSize(QtCore.QSize(22, 22))
        self.btnTask.setObjectName("btnTask")
        self.verticalLayout_10.addWidget(self.btnTask)
        self.verticalLayout_9.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnCreateTask = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateTask.sizePolicy().hasHeightForWidth())
        self.btnCreateTask.setSizePolicy(sizePolicy)
        self.btnCreateTask.setStyleSheet("QPushButton {\n"
"  \n"
"    background-color: rgb(213, 203, 203);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: rgb(91, 91, 91);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/plus-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreateTask.setIcon(icon7)
        self.btnCreateTask.setIconSize(QtCore.QSize(22, 22))
        self.btnCreateTask.setObjectName("btnCreateTask")
        self.verticalLayout_4.addWidget(self.btnCreateTask)
        self.btnDeleteTask = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteTask.sizePolicy().hasHeightForWidth())
        self.btnDeleteTask.setSizePolicy(sizePolicy)
        self.btnDeleteTask.setStyleSheet("QPushButton {\n"
" background-color: rgb(213, 203, 203);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: rgb(91, 91, 91);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteTask.setIcon(icon8)
        self.btnDeleteTask.setIconSize(QtCore.QSize(22, 22))
        self.btnDeleteTask.setObjectName("btnDeleteTask")
        self.verticalLayout_4.addWidget(self.btnDeleteTask)
        self.verticalLayout_9.addWidget(self.frame_7, 0, QtCore.Qt.AlignBottom)
        self.stackedWidgetLeftMenu.addWidget(self.page_1)
        self.verticalLayout_3.addWidget(self.stackedWidgetLeftMenu)
        self.horizontalLayout_2.addWidget(self.leftSubMenu, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.frame)
        self.centerMenu = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerMenu.sizePolicy().hasHeightForWidth())
        self.centerMenu.setSizePolicy(sizePolicy)
        self.centerMenu.setStyleSheet("QFrame#centerMenu{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.0113636, x2:0.314, y2:0.409455, stop:0.0909091 rgba(29, 67, 155, 255), stop:0.903409 rgba(28, 28, 28, 255));\n"
"}")
        self.centerMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centerMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centerMenu.setObjectName("centerMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centerMenu)
        self.verticalLayout_8.setContentsMargins(0, 33, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.MainStack = QtWidgets.QStackedWidget(self.centerMenu)
        self.MainStack.setStyleSheet("QStackedWidget#MainStack{\n"
"background-color: rgb(28, 28, 28);}")
        self.MainStack.setObjectName("MainStack")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.page_11)
        self.frame_4.setStyleSheet("color: white;\n"
"background-color: rgb(28, 28, 28)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(3, 3, 3, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_23 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setStyleSheet("color: white;\n"
"background-color: rgb(28, 28, 28)")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.frame_23)
        self.tableWidget_1.setStyleSheet(" QTableWidget {\n"
"    }\n"
"    QTableWidget QHeaderView::section {\n"
"    color: black;\n"
"\n"
"    background-color: rgb(173, 142, 57);\n"
"    \n"
"\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"    }\n"
"QTableWidget::item {\n"
"        color:black;\n"
"        \n"
"    \n"
"    background-color: rgb(217, 217, 217);\n"
"\n"
"    }")
        self.tableWidget_1.setAlternatingRowColors(False)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(0)
        self.tableWidget_1.setRowCount(0)
        self.verticalLayout_25.addWidget(self.tableWidget_1)
        self.gridLayout.addWidget(self.frame_23, 0, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_4)
        self.frame_21.setStyleSheet("")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_3.setContentsMargins(5, 0, 3, 5)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnAdd_row = QtWidgets.QPushButton(self.frame_21)
        self.btnAdd_row.setStyleSheet("QPushButton {\n"
"padding: 3px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,150)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnAdd_row.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd_row.setIcon(icon9)
        self.btnAdd_row.setIconSize(QtCore.QSize(14, 14))
        self.btnAdd_row.setObjectName("btnAdd_row")
        self.horizontalLayout_3.addWidget(self.btnAdd_row)
        self.btnDelete_row = QtWidgets.QPushButton(self.frame_21)
        self.btnDelete_row.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnDelete_row.setFont(font)
        self.btnDelete_row.setStyleSheet("QPushButton {\n"
"padding: 3px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,150)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnDelete_row.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete_row.setIcon(icon10)
        self.btnDelete_row.setIconSize(QtCore.QSize(14, 14))
        self.btnDelete_row.setObjectName("btnDelete_row")
        self.horizontalLayout_3.addWidget(self.btnDelete_row)
        self.gridLayout.addWidget(self.frame_21, 0, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setContentsMargins(0, 5, 5, 3)
        self.verticalLayout_19.setSpacing(3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.btnAdd_column = QtWidgets.QPushButton(self.frame_3)
        self.btnAdd_column.setStyleSheet("QPushButton {\n"
"padding: 3px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,150)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnAdd_column.setText("")
        self.btnAdd_column.setIcon(icon9)
        self.btnAdd_column.setIconSize(QtCore.QSize(14, 14))
        self.btnAdd_column.setObjectName("btnAdd_column")
        self.verticalLayout_19.addWidget(self.btnAdd_column)
        self.btnDelete_column = QtWidgets.QPushButton(self.frame_3)
        self.btnDelete_column.setStyleSheet("QPushButton {\n"
"padding: 3px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,150)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnDelete_column.setText("")
        self.btnDelete_column.setIcon(icon10)
        self.btnDelete_column.setIconSize(QtCore.QSize(14, 14))
        self.btnDelete_column.setObjectName("btnDelete_column")
        self.verticalLayout_19.addWidget(self.btnDelete_column)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 2, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.MainStack.addWidget(self.page_11)
        self.page_22 = QtWidgets.QWidget()
        self.page_22.setObjectName("page_22")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_22)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_15 = QtWidgets.QFrame(self.page_22)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_15.setStyleSheet("color: white;\n"
"background-color: rgb(28, 28, 28)")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_20.setContentsMargins(3, 3, 3, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_15)
        font = QtGui.QFont()
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet(" QTableWidget {\n"
"    }\n"
"    QTableWidget QHeaderView::section {\n"
"    color: black;\n"
"\n"
"    background-color: rgb(173, 142, 57);\n"
"    \n"
"\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"    }\n"
"QTableWidget::item {\n"
"        color:black;\n"
"        \n"
"    \n"
"    background-color: rgb(217, 217, 217);\n"
"\n"
"    }")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_20.addWidget(self.tableWidget_2)
        self.verticalLayout_12.addWidget(self.frame_15)
        self.frame_19 = QtWidgets.QFrame(self.page_22)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_19.setStyleSheet("color: white;\n"
"background-color: rgb(28, 28, 28)")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_22.setContentsMargins(15, 10, 15, 25)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.line_4 = QtWidgets.QFrame(self.frame_19)
        self.line_4.setMinimumSize(QtCore.QSize(0, 0))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_22.addWidget(self.line_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_19)
        self.frame_6.setStyleSheet("background-color: rgb(28, 28, 28);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setContentsMargins(0, 15, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_17 = QtWidgets.QFrame(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.frame_17.setFont(font)
        self.frame_17.setStyleSheet("background-color: rgb(28, 28, 28);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_22 = QtWidgets.QFrame(self.frame_17)
        self.frame_22.setStyleSheet("border-width: no;\n"
"")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineFIO_22 = QtWidgets.QLineEdit(self.frame_22)
        self.lineFIO_22.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(11)
        self.lineFIO_22.setFont(font)
        self.lineFIO_22.setStyleSheet("QLineEdit {\n"
"background-color: rgb(37, 37, 37);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 0.5px;\n"
"padding-left: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:Pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"")
        self.lineFIO_22.setObjectName("lineFIO_22")
        self.horizontalLayout_7.addWidget(self.lineFIO_22)
        self.verticalLayout_21.addWidget(self.frame_22)
        self.frame_16 = QtWidgets.QFrame(self.frame_17)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineGroup_22 = QtWidgets.QLineEdit(self.frame_16)
        self.lineGroup_22.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(11)
        self.lineGroup_22.setFont(font)
        self.lineGroup_22.setStyleSheet("QLineEdit {\n"
"background-color: rgb(37, 37, 37);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 0.5px;\n"
"padding-left: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:Pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"")
        self.lineGroup_22.setObjectName("lineGroup_22")
        self.horizontalLayout_10.addWidget(self.lineGroup_22)
        self.lineGpa_22 = QtWidgets.QLineEdit(self.frame_16)
        self.lineGpa_22.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(11)
        self.lineGpa_22.setFont(font)
        self.lineGpa_22.setStyleSheet("QLineEdit {\n"
"background-color: rgb(37, 37, 37);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 0.5px;\n"
"padding-left: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:Pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"")
        self.lineGpa_22.setObjectName("lineGpa_22")
        self.horizontalLayout_10.addWidget(self.lineGpa_22)
        self.verticalLayout_21.addWidget(self.frame_16)
        self.horizontalLayout_11.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_6)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_16.setContentsMargins(10, 10, 0, 0)
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.btnDeleteFio_22 = QtWidgets.QPushButton(self.frame_18)
        self.btnDeleteFio_22.setMinimumSize(QtCore.QSize(100, 30))
        self.btnDeleteFio_22.setStyleSheet("QPushButton {\n"
"color: white;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255, 50)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnDeleteFio_22.setObjectName("btnDeleteFio_22")
        self.verticalLayout_16.addWidget(self.btnDeleteFio_22)
        self.btnSavePerson_22 = QtWidgets.QPushButton(self.frame_18)
        self.btnSavePerson_22.setMinimumSize(QtCore.QSize(100, 30))
        self.btnSavePerson_22.setStyleSheet("QPushButton {\n"
"color: white;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255, 50)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnSavePerson_22.setObjectName("btnSavePerson_22")
        self.verticalLayout_16.addWidget(self.btnSavePerson_22)
        self.horizontalLayout_11.addWidget(self.frame_18)
        self.verticalLayout_22.addWidget(self.frame_6)
        self.verticalLayout_12.addWidget(self.frame_19)
        self.MainStack.addWidget(self.page_22)
        self.page_33 = QtWidgets.QWidget()
        self.page_33.setObjectName("page_33")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_33)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea = QtWidgets.QScrollArea(self.page_33)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 815, 582))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_23.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.scrollArea)
        self.frame_33 = QtWidgets.QFrame(self.page_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setStyleSheet("background-color: rgb(28, 28, 28);")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_8.setContentsMargins(15, 20, 15, 25)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineTopic = QtWidgets.QLineEdit(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTopic.sizePolicy().hasHeightForWidth())
        self.lineTopic.setSizePolicy(sizePolicy)
        self.lineTopic.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(11)
        self.lineTopic.setFont(font)
        self.lineTopic.setStyleSheet("QLineEdit {\n"
"background-color: rgb(37, 37, 37);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 0.5px;\n"
"padding-left: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:Pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"")
        self.lineTopic.setObjectName("lineTopic")
        self.horizontalLayout_8.addWidget(self.lineTopic)
        self.btnSaveTopic = QtWidgets.QPushButton(self.frame_33)
        self.btnSaveTopic.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btnSaveTopic.setFont(font)
        self.btnSaveTopic.setStyleSheet("QPushButton {\n"
"color: white;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255, 50)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnSaveTopic.setObjectName("btnSaveTopic")
        self.horizontalLayout_8.addWidget(self.btnSaveTopic)
        self.btnDeleteTopic = QtWidgets.QPushButton(self.frame_33)
        self.btnDeleteTopic.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btnDeleteTopic.setFont(font)
        self.btnDeleteTopic.setStyleSheet("QPushButton {\n"
"color: white;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background-color: rgba(255,255,255,50)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255, 100)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btnDeleteTopic.setObjectName("btnDeleteTopic")
        self.horizontalLayout_8.addWidget(self.btnDeleteTopic)
        self.verticalLayout_13.addWidget(self.frame_33)
        self.MainStack.addWidget(self.page_33)
        self.page_44 = QtWidgets.QWidget()
        self.page_44.setObjectName("page_44")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_44)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_11 = QtWidgets.QFrame(self.page_44)
        self.frame_11.setStyleSheet("background-color: rgb(28, 28, 28);\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_15.setContentsMargins(15, 15, 15, 25)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("text-align: left;\n"
"color: rgb(139, 211, 206);\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon11)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_15.addWidget(self.pushButton_2)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet(" QTableWidget {\n"
"    }\n"
"    QTableWidget QHeaderView::section {\n"
"    color: black;\n"
"\n"
"    background-color: rgb(173, 142, 57);\n"
"    \n"
"\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"    }\n"
"QTableWidget::item {\n"
"        color:black;\n"
"        \n"
"    \n"
"    background-color: rgb(217, 217, 217);\n"
"\n"
"    }")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_15.addWidget(self.frame_12)
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 16)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.line_3 = QtWidgets.QFrame(self.frame_14)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_18.addWidget(self.line_3)
        self.verticalLayout_15.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setStyleSheet("background-color: rgb(32, 32, 32);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.le_write_task = QtWidgets.QLineEdit(self.frame_13)
        self.le_write_task.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(13)
        self.le_write_task.setFont(font)
        self.le_write_task.setToolTip("")
        self.le_write_task.setStyleSheet("QLineEdit {\n"
"padding-left: 15px;\n"
"border-radius: 5px;\n"
"background-color: rgb(37, 37, 37);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"QLineEdit:Pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"")
        self.le_write_task.setObjectName("le_write_task")
        self.horizontalLayout_5.addWidget(self.le_write_task)
        self.btn_new_task = QtWidgets.QPushButton(self.frame_13)
        self.btn_new_task.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_new_task.setStyleSheet("QPushButton {\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255,255,100)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
"background-color: rgba(255,255,255,150)\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(255,255,255)\n"
"}\n"
"")
        self.btn_new_task.setText("")
        self.btn_new_task.setIcon(icon9)
        self.btn_new_task.setIconSize(QtCore.QSize(30, 30))
        self.btn_new_task.setObjectName("btn_new_task")
        self.horizontalLayout_5.addWidget(self.btn_new_task)
        self.verticalLayout_15.addWidget(self.frame_13, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_14.addWidget(self.frame_11)
        self.MainStack.addWidget(self.page_44)
        self.verticalLayout_8.addWidget(self.MainStack)
        self.horizontalLayout.addWidget(self.centerMenu)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidgetLeftMenu.setCurrentIndex(0)
        self.MainStack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Планировщик командирской работы"))
        self.label_2.setText(_translate("MainWindow", "МЧС России"))
        self.btnHome.setToolTip(_translate("MainWindow", "Отчёт"))
        self.btnHome.setText(_translate("MainWindow", " Отчёт"))
        self.btnPerson.setToolTip(_translate("MainWindow", "Журнал"))
        self.btnPerson.setText(_translate("MainWindow", " Журнал"))
        self.btnTopic.setToolTip(_translate("MainWindow", "Список тем"))
        self.btnTopic.setText(_translate("MainWindow", " Список тем"))
        self.helpBtn.setToolTip(_translate("MainWindow", "Планировщик"))
        self.helpBtn.setText(_translate("MainWindow", " Планировщик"))
        self.settingBtn.setToolTip(_translate("MainWindow", "Настройки"))
        self.settingBtn.setText(_translate("MainWindow", " Настройки"))
        self.btnTask.setText(_translate("MainWindow", "Задачи"))
        self.btnCreateTask.setText(_translate("MainWindow", "Создать"))
        self.btnDeleteTask.setText(_translate("MainWindow", "Удалить"))
        self.btnAdd_row.setToolTip(_translate("MainWindow", "Удаляет выбранную строк"))
        self.btnDelete_row.setToolTip(_translate("MainWindow", "Удаляет выбранную строк"))
        self.btnAdd_column.setToolTip(_translate("MainWindow", "Удаляет выбранную строк"))
        self.btnDelete_column.setToolTip(_translate("MainWindow", "Удаляет выбранную строк"))
        self.lineFIO_22.setPlaceholderText(_translate("MainWindow", "Фамилия Имя Отчество"))
        self.lineGroup_22.setPlaceholderText(_translate("MainWindow", "№ группы"))
        self.lineGpa_22.setPlaceholderText(_translate("MainWindow", "Средний балл"))
        self.btnDeleteFio_22.setText(_translate("MainWindow", "Удалить"))
        self.btnSavePerson_22.setText(_translate("MainWindow", "Сохранить"))
        self.lineTopic.setPlaceholderText(_translate("MainWindow", "Введите тему, которую хотите добавить"))
        self.btnSaveTopic.setText(_translate("MainWindow", "Сохранить"))
        self.btnSaveTopic.setShortcut(_translate("MainWindow", "Return"))
        self.btnDeleteTopic.setToolTip(_translate("MainWindow", "Удаляет выбранную строк"))
        self.btnDeleteTopic.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_2.setText(_translate("MainWindow", "Задачи"))
        self.le_write_task.setPlaceholderText(_translate("MainWindow", "Добавить задачу"))
import Designer.res_rc
